namespace epsilon.CodeAnalysis.Syntax;

public enum SyntaxKind {
    BadToken,

    // Trivia
    SkippedTextTrivia,
    WhitespaceTrivia,
    LineBreakTrivia,
    SingleLineCommentTrivia,
    MultiLineCommentTrivia,

    // Tokens
    StringToken,
    NumberToken,
    PlusToken,
    PlusEqualsToken,
    MinusToken,
    MinusEqualsToken,
    StarToken,
    StarEqualsToken,
    SlashToken,
    SlashEqualsToken,
    BangToken,
    EqualsToken,
    AmpersandToken,
    AmpersandEqualsToken,
    AmpersandAmpersandToken,
    PipeToken,
    PipeEqualsToken,
    PipePipeToken,
    EqualsEqualsToken,
    BangEqualsToken,
    LessToken,
    LessOrEqualsToken,
    GreaterToken,
    GreaterOrEqualsToken,
    OpenParenthesisToken,
    CloseParenthesisToken,
    OpenBraceToken,
    CloseBraceToken,
    ColonToken,
    SemicolonToken,
    CommaToken,
    TildeToken,
    HatToken,
    HatEqualsToken,
    EndOfFileToken,
    IdentifierToken,

    // Keywords
    AsKeyword,
    ContinueKeyword,
    BreakKeyword,
    ElseKeyword,
    FalseKeyword,
    ForKeyword,
    FunKeyword,
    IfKeyword,
    ValKeyword,
    ReturnKeyword,
    ToKeyword,
    TrueKeyword,
    VarKeyword,
    WhileKeyword,
    DoKeyword,

    // Nodes
    CompilationUnit,
    FunctionDeclaration,
    GlobalStatement,
    Parameter,
    TypeClause,
    ElseClause,
    VariableDeclarationClause,
    Initializer,

    // Statements
    BlockStatement,
    VariableDeclarationStatement,
    IfStatement,
    WhileStatement,
    DoWhileStatement,
    ForStatement,
    BreakStatement,
    ContinueStatement,
    ReturnStatement,
    ExpressionStatement,

    // Expressions
    LiteralExpression,
    NameExpression,
    UnaryExpression,
    BinaryExpression,
    CompoundAssignmentExpression,
    ParenthesizedExpression,
    AssignmentExpression,
    CallExpression,
    TokenExpression,
}
